server:
  port: 8081
  servlet.context-path: marketing-company
spring:
  application:
    name: MarketingCompany
  mvc:
    servlet:
      path: /mvc
swagger:
  application:
    version: @project.version@
    name: MarketingCompany
    description: @project.description@