server:
  port: 8081
  servlet:
    context-path: /marketing-company
spring:
  application:
    name: MarketingCompany
  mvc:
    servlet:
      path: /mvc
#swagger.application.name=MarketingCompany
# The @ delimiter is used to get config properties from the POM
#swagger.application.description=@project.description@
#swagger.application.version=@project.version@